# Generated by Django 4.2.3 on 2023-07-23 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_discount_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='popularity',
            options={'verbose_name_plural': 'Popularity'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name_plural': 'Product rating'},
        ),
        migrations.AlterModelOptions(
            name='sellerrating',
            options={'verbose_name_plural': 'Seller rating'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 14, 21, 27, 951847, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='popularity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 14, 21, 27, 952846, tzinfo=datetime.timezone.utc)),
        ),
    ]
