# Generated by Django 4.2.3 on 2023-07-24 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_popularity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 12, 21, 41, 74875, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='popularity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 12, 21, 41, 76161, tzinfo=datetime.timezone.utc)),
        ),
    ]
