# Generated by Django 4.2.3 on 2023-08-09 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productrating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAMValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'RAM values',
            },
        ),
        migrations.CreateModel(
            name='StorageValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Storage values',
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 12, 7, 28, 94000, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='popularity',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 12, 7, 28, 98469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 12, 7, 28, 94000, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellerrating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 12, 7, 28, 98469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('storage_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.storagevalue')),
            ],
            options={
                'verbose_name_plural': 'Storage',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ramvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name_plural': 'RAM',
            },
        ),
    ]
