# Generated by Django 4.2.3 on 2023-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ramvalue_storagevalue_alter_discount_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='popularity',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sellerrating',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
