# Generated by Django 4.2.3 on 2023-08-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_discount_finish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='score',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='sellerrating',
            old_name='score',
            new_name='value',
        ),
    ]
