# Generated by Django 4.2.3 on 2023-08-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_score_productrating_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='minus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='plus',
            field=models.TextField(null=True),
        ),
    ]
