# Generated by Django 4.2.3 on 2023-08-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_productrating_minus_productrating_plus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerRating',
        ),
    ]
