# Generated by Django 4.2.3 on 2023-07-20 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_alter_comment_date_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 17, 59, 39, 552139, tzinfo=datetime.timezone.utc)),
        ),
    ]
