# Generated by Django 4.2.3 on 2023-07-24 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0009_alter_comment_date_alter_productincart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 16, 1, 0, 357376, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 16, 1, 0, 354557, tzinfo=datetime.timezone.utc)),
        ),
    ]
