# Generated by Django 4.2.3 on 2023-08-06 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0013_alter_comment_date_alter_productincart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 20, 59, 16, 314169, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
