# Generated by Django 4.2.3 on 2023-08-09 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0014_alter_productincart_date_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 12, 7, 28, 101854, tzinfo=datetime.timezone.utc)),
        ),
    ]
