# Generated by Django 4.2.3 on 2023-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0015_alter_productincart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
