# Generated by Django 4.2.3 on 2023-08-19 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_productrating_minus_productrating_plus'),
        ('buyers', '0016_alter_productincart_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favorites',
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
    ]
